---

# Major release of drupal in use (6, 7, 8, etc.). Be sure to update the core
# version inside the drupal.make file if you change the major version here.
drupal_major_version: 7

# The path where Drupal will be downloaded and installed.
drupal_core_path: "/var/www/drupal"
drupal_domain: "local.store.bbc.com"
drupal_mysql_user: drupal
drupal_mysql_password: password
drupal_mysql_database: bbcstore_com
drupal_database_dump: dump.sql.gz

# Vagrant hostname and IP configuration.
vagrant_hostname: local.store.bbc.com
vagrant_ip: 

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - local_path: ~/workspace/store/docroot
    destination: /var/www/drupal
    excluded_paths: [".git/"]
    id: drupal
    type: rsync

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
mysql_root_password: root

# TODO - REMOVE THIS VARIABLE AFTER ANSIBLE 1.8.3+
drush_keep_updated: yes
drush_version: master

# Comment out any extra utilities you don't want to install.
installed_extras:
  - memcached
  - phpmyadmin
  - xdebug
  - xhprof
  - solr

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
  - "8080"
  - "8443"

apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
  - {servername: "local.xhprof.com", documentroot: "/usr/share/php/xhprof_html"}

php_memory_limit: "256M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0
