---
- name: Create Drupal database.
  mysql_db: "db={{ drupal_mysql_database }} state=present"

- name: Create Drupal database user.
  mysql_user: "name={{ drupal_mysql_user }} password={{ drupal_mysql_password }} priv=*.*:ALL state=present"

- name: Copy database dump.
  copy: "src={{ database_dump }} dest=/tmp/database_dump.sql.gz"

- name: Import database.
  mysql_db: "name={{ drupal_mysql_database }} state=import target=/tmp/database_dump.sql.gz"

- name: Remove default virtualhost file.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart webserver

- name: Update ownership of all files within drupal_core_path.
  file:
    path: "{{ drupal_core_path }}"
    owner: vagrant
    group: www-data
    mode: 0775
    recurse: yes
