---
- name: Create bbcstore Solr directory.
  file:
    path: "/opt/solr/bbcstore"
    state: "directory"

- name: Create bbcstore/data Solr directory.
  file:
    path: "/opt/solr/bbcstore/data"
    state: "directory"

- name: Set correct permissions on Solr directories.
  command: "chown tomcat6:tomcat6 /opt/solr/bbcstore/data/ -R"

- name: Copy Solr config from Drupal.
  command: "cp -r {{ drupal_core_path }}/sites/all/modules/contrib/search_api_solr/solr-conf/4.x /opt/solr/bbcstore/conf"

- name: Move solr.xml config to remote.
  copy:
    src: "solr.xml"
    dest: "/opt/solr"
    owner: tomcat6
    group: tomcat6
